PREFIX cvo:  <http://purl.jp/bio/10/clinvar/>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT {
    GRAPH <http://example.com/clinvar> {
        ?variant dct:identifier ?tgv_id ;
           ?p ?o .
    }
    GRAPH <http://togovar.biosciencedbc.jp/variant/annotation/clinvar> {
        ?variant dct:identifier ?variation_id ;
            ?p2 ?o2 .
    } 
    GRAPH <http://togovar.biosciencedbc.jp/clinvar> {
        ?clinvar cvo:accession ?vcv .
        ?_rcv ?p4 ?o4 .
        ?_interpreted_condition ?p5 ?o5 .
    }
} 
WHERE { 
   SERVICE <https://grch38.togovar.org/sparql> {
       SELECT *
       WHERE {
            VALUES ?tgv_id { "tgv4318015" }

            GRAPH <http://togovar.biosciencedbc.jp/variant> {
                ?variant dct:identifier ?tgv_id ;
                        ?p ?o .
            }
            
            GRAPH <http://togovar.biosciencedbc.jp/variant/annotation/clinvar> {
            ?variant dct:identifier ?variation_id ; ?p2 ?o2 .
            BIND(IRI(CONCAT("http://ncbi.nlm.nih.gov/clinvar/variation/", ?variation_id)) AS ?clinvar)
        }
            
        GRAPH <http://togovar.biosciencedbc.jp/clinvar> {
            ?clinvar a cvo:VariationArchiveType ;
                rdfs:label ?title ;
                cvo:accession ?vcv ;
                cvo:interpreted_record ?interpreted_record .
            ?interpreted_record cvo:review_status ?review_status ;
                 cvo:rcv_accession ?_rcv ;
                 sio:SIO_000628 ?sio_accession .
            ?sio_accession dct:references ?dbsnp . 
            ?dbsnp rdfs:seeAlso ?rs_id .

            ?_rcv cvo:interpretation ?interpretation ;
            cvo:date_last_evaluated ?last_evaluated ;
            cvo:interpreted_condition_list/cvo:interpreted_condition ?_interpreted_condition .

            ?_interpreted_condition rdfs:label ?condition .

            OPTIONAL {
            ?_interpreted_condition dct:source ?db ;
                dct:identifier ?medgen .
            FILTER(?db IN ("MedGen"))
    }       
}
    

 
            
    


   


