PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX so: <http://purl.obolibrary.org/obo/SO_>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX wi: <http://http://purl.org/ontology/wi/core#>
PREFIX eco: <http://http://purl.obolibrary.org/obo/eco.owl#>
PREFIX prov: <http://http://http://www.w3.org/ns/prov#>
PREFIX pav: <http://http://http://purl.org/pav/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dto: <http://diseasetargetontology.org/dto/>
PREFIX geno: <http://purl.obolibrary.org/obo/geno/>

select * where {
    SERVICE <http://rdf.disgenet.org/sparql/> {
        #VALUES ?variant {<http://identifiers.org/dbsnp/rs6003> }
        GRAPH <http://rdf.disgenet.org> {
            SELECT DISTINCT ?variant ?symbol_label ?disease_label ?source_title ?vda ?description
            
WHERE {
                VALUES ?variant { <http://identifiers.org/dbsnp/rs6003> }            
 	?variant a so:0001060 ; 
           so:associated_with ?gene ;
           ^sio:SIO_000628 ?vda .
    ?vda dcterms:description ?description .
    ?gda sio:SIO_000628 ?gene ;
         sio:SIO_000253 ?source .
    ?source dcterms:title ?source_title .
    ?gene sio:SIO_000205 ?gene_symbol .
    ?gene_symbol rdfs:label ?symbol_label .
    ?gda sio:SIO_000628 ?disease .
    ?disease rdfs:label ?disease_label .
           
               
    FILTER (?variant=<http://identifiers.org/dbsnp/rs6003>)
} LIMIT 20

        }
    }PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX so: <http://purl.obolibrary.org/obo/SO_>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX wi: <http://http://purl.org/ontology/wi/core#>
PREFIX eco: <http://http://purl.obolibrary.org/obo/eco.owl#>
PREFIX prov: <http://http://http://www.w3.org/ns/prov#>
PREFIX pav: <http://http://http://purl.org/pav/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dto: <http://diseasetargetontology.org/dto/>
PREFIX geno: <http://purl.obolibrary.org/obo/geno/>

select * where {
    SERVICE <http://rdf.disgenet.org/sparql/> {
        #VALUES ?variant {<http://identifiers.org/dbsnp/rs6003> }
        GRAPH <http://rdf.disgenet.org> {
            SELECT DISTINCT ?variant ?symbol_label ?disease_label ?source_title ?vda ?description
            
WHERE {
                VALUES ?variant { <http://identifiers.org/dbsnp/rs6003> }            
 	?variant a so:0001060 ; 
           so:associated_with ?gene ;
           ^sio:SIO_000628 ?vda .
    ?vda dcterms:description ?description .
    ?gda sio:SIO_000628 ?gene ;
         sio:SIO_000253 ?source .
    ?source dcterms:title ?source_title .
    ?gene sio:SIO_000205 ?gene_symbol .
    ?gene_symbol rdfs:label ?symbol_label .
    ?gda sio:SIO_000628 ?disease .
    ?disease rdfs:label ?disease_label .
           
               
    FILTER (?variant=<http://identifiers.org/dbsnp/rs6003>)
} LIMIT 20

        }
    }
}